### Get all
GET http://localhost:5000/api/expenses

### Get id
GET http://localhost:5000/api/expenses/3

### Get month
GET http://localhost:5000/api/expenses/month/6

### Get date
GET http://localhost:5000/api/expenses/date/2022-01-15

### Get shop
GET http://localhost:5000/api/expenses/shop/zalando

### Get category
GET http://localhost:5000/api/expenses/category/records

###Get amount
GET http://localhost:5000/api/expenses/amount/100

### Post expense
POST http://localhost:5000/api/expenses/ HTTP/1.1
content-type: application/json

{
 "date": "2022-06-25",
 "category": "smokes",
 "shop": "rkioksi",
 "amount": 666
}

### Update expense
PUT http://localhost:5000/api/expenses HTTP/1.1
content-type: application/json

{
 "id": 72,
 "date": "2022-06-25",
 "category": "carpart",
 "shop": "motonet",
 "amount": 500
}

### Delete expense
DELETE http://localhost:5000/api/expenses/15